name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Classic Stats
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.classic.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, repositories
            plugin_lines: yes
            
        - name: Most Used
          uses: lowlighter/metrics@latest
          with:
              filename: metrics.plugin.languages.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: ""
              plugin_languages: yes
              plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
              plugin_languages_limit: 4
              
        - name: Youtube Music
          uses: lowlighter/metrics@latest
          with: 
            filename: metrics.plugin.music.playlist.svg
            token: NOT_NEEDED
            base: ""
            plugin_music: yes
            plugin_music_playlist: >-
              https://music.youtube.com/playlist?list=PLGfsZg8IfeS3bVTe5HmTViEHIEYaBd_Bq
            
        - name: Full-year calendar
          uses: lowlighter/metrics@latest
          with: 
            filename: metrics.plugin.isocalendar.fullyear.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_isocalendar: yes
            plugin_isocalendar_duration: full-year
